<h1> EDA

<h3> Nesse jupyter notebook iremos analisar os dados de produtos e vendas da Vai Store

Primeiro vamos começar omportando as bibliotecas que serão utilizadas ao longo do projeto

In [2]:
import pandas as pd

Agora vamos fazer uma análise exploratória dos dados disponíveis para os **produtos**

In [3]:
produtos = pd.read_csv('Dados Projeto\produto.csv', index_col = 0)

<>:1: SyntaxWarning: invalid escape sequence '\p'
<>:1: SyntaxWarning: invalid escape sequence '\p'
C:\Users\felip\AppData\Local\Temp\ipykernel_31820\3475921097.py:1: SyntaxWarning: invalid escape sequence '\p'
  produtos = pd.read_csv('Dados Projeto\produto.csv', index_col = 0)

In [4]:
produtos.head()

,NOME_PRODUTO,CATEGORIA,SUBCATEGORIA
SKU,,,
3.0,COCO RALADO GROSSO KG ...,Doceria,Confeitaria
4.0,ICE TEA LEAO LATA 340ML ...,NaN,NaN
5.0,TAHINE ISTAMBUL 200G ...,Pelo Mundo,Pastas Árabes
6.0,AMENDOIM MOIDO KG ...,Castanhas & Oleaginosas,Oleaginosas moídas
7.0,HALAWI ISTAMBUL LATA 500G ...,Pelo Mundo,Pastas Árabes

Agora vamos fazer a análise exploratória dos dados para as **vendas**

In [5]:
vendas = pd.read_csv(r"C:\Users\felip\OneDrive\Programação\Vai Academy\Projeto_final\Dados Projeto\vendas.csv", index_col = 0, )

In [6]:
vendas.head(10000)

,COD_VENDA,COD_FILIAL,FILIAL,DATA_ATEND,SKU,UNID,QTD_VENDA,FATUR_VENDA,CLI_CPF
COD_ATEND,,,,,,,,,
000304564.299.0101042.20240102,000304564.299.0101042.20240102.000009.02,101042,SHOPPING,2024-01-02,9,KG,0.258,18.04,ec0abf3f4220
000374698.258.0101032.20240102,000374698.258.0101032.20240102.000009.10,101032,RUA,2024-01-02,9,KG,0.064,4.50,83d596ee0acf
000383551.256.0101032.20240102,000383551.256.0101032.20240102.000009.02,101032,RUA,2024-01-02,9,KG,0.164,11.49,46f63c18e055
000383533.256.0101032.20240102,000383533.256.0101032.20240102.000009.02,101032,RUA,2024-01-02,9,KG,0.202,14.13,6def1d35e2fe
000432095.257.0101032.20240102,000432095.257.0101032.20240102.000051.06,101032,RUA,2024-01-02,51,KG,0.086,6.87,1576e1a36394
...,...,...,...,...,...,...,...,...,...
000134285.390.0101032.20240109,000134285.390.0101032.20240109.013805.02,101032,RUA,2024-01-09,13805,KG,0.140,3.77,14443c1f8f36
000376002.258.0101032.20240109,000376002.258.0101032.20240109.013805.03,101032,RUA,2024-01-09,13805,KG,0.108,2.91,d46b09284e84
000311977.298.0101042.20240109,000311977.298.0101042.20240109.013805.06,101042,SHOPPING,2024-01-09,13805,KG,0.118,3.53,6220ea3095e3
000312028.298.0101042.20240109,000312028.298.0101042.20240109.013805.04,101042,SHOPPING,2024-01-09,13805,KG,0.206,6.16,73dd0fc4d200
000306324.299.0101042.20240109,000306324.299.0101042.20240109.013805.01,101042,SHOPPING,2024-01-09,13805,KG,0.068,2.03,6f5057ea1ee4

In [7]:
nan_count_CPF = vendas['CLI_CPF'].isna().sum()
print(f"Número de valores ausentes na coluna 'CLI_CPF': {nan_count_CPF}")

Número de valores ausentes na coluna 'CLI_CPF': 0